### ISSUE TITLE
Is there a release in sight for the `lookupContainsRange` functions?

### ISSUE THREAD

**Issue by gnidan** [sebastian-philipp/r-tree#7]
I can work around it in the meantime by using cabal sandboxes and git, but it'd be nice if those changes made it to Hackage :)

**Comment by sebastian-philipp** [comment]
Thanks for poking. I'll try to upload a new release shortly.

**Comment by alexanderkjeldaas** [comment]
Any update forthcoming?

**Comment by sebastian-philipp** [comment]
Working on it right now.

**Comment by sebastian-philipp** [comment]
Finally Fixed after 5 years! https://hackage.haskell.org/package/data-r-tree-0.6.0
