### ISSUE TITLE
error "node: empty"

### ISSUE THREAD

**Issue by kaiko** [sebastian-philipp/r-tree#8]
I get occasionally error "node: empty" at Base.hs:125.
Why this line doesn't return Empty value?

**Comment by sebastian-philipp** [comment]
Hi kaiko, do you have a reproducible example?

**Comment by kaiko** [comment]
No. Working on it.

**Comment by sebastian-philipp** [comment]
any update?

**Comment by BurningWitness** [comment]
No longer relevant.
